apiVersion: v1
kind: Namespace
metadata:
  name: data-storage   # Für MinIO & Postgres
  labels:
    # Damit ArgoCD weiß, dass es diesen Namespace verwalten darf
    argocd.argoproj.io/managed-by: argocd
---
apiVersion: v1
kind: Namespace
metadata:
  name: mlops          # Für MLflow & Jupyter
  labels:
    argocd.argoproj.io/managed-by: argocd
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring     # Für Prometheus & Grafana (Screenshot)
  labels:
    argocd.argoproj.io/managed-by: argocd
---
apiVersion: v1
kind: Namespace
metadata:
  name: argo-events    # Für die Zusatzaufgabe
  labels:
    argocd.argoproj.io/managed-by: argocd